apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mysql
    tier: database
  name: mysql-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  my.cnf: |
    [mysqld]
    innodb_buffer_pool_size = 128M
    innodb_log_buffer_size = 8M
    key_buffer_size = 16M
    query_cache_size = 0
    max_connections = 20
    tmp_table_size = 32M
    max_heap_table_size = 32M
